require('dotenv').config();
const axios = require('axios');
const AIAgent = require('../model/aiAgentModel');

console.log('Hugging Face API Key:', process.env.HUGGINGFACE_API_KEY);

// Get Embeddings using Hugging Face API
exports.getEmbeddings = async (text) => {
    try {
        const response = await axios.post(
            'https://api-inference.huggingface.co/models/sentence-transformers/all-MiniLM-L6-v2',
            { inputs: [text] }, // Wrap the text in an array
            {
                headers: {
                    Authorization: `Bearer ${process.env.HUGGINGFACE_API_KEY}`,
                },
            }
        );
        console.log('Hugging Face Embeddings Response:', response.data);
        if (response.data && Array.isArray(response.data) && response.data[0]) {
            return response.data[0];
        }
        console.warn('No embeddings generated by Hugging Face API');
        return [];
    } catch (error) {
        console.error('Error fetching embeddings from Hugging Face:', error.response?.data || error.message);
        return [];
    }
};

// Retrieve documents from MongoDB based on embeddings
exports.retrieveDocuments = async (embeddings, context) => {
    try {
        if (typeof context !== 'string' || !context.trim()) {
            console.error('Invalid context provided for document retrieval.');
            return [];
        }

        const documents = await AIAgent.find({
            videoContext: { $regex: context, $options: 'i' }
        }).limit(5);

        console.log('Retrieved Documents:', documents); // Log the retrieved documents
        return documents.map(doc => doc.response);
    } catch (error) {
        console.error('Error retrieving documents:', error.message);
        return [];
    }
};

// Generate response using a generative model from Hugging Face
exports.generateResponse = async (query, documents = []) => {
    try {
        if (!Array.isArray(documents) || documents.length === 0) {
            documents = ["No relevant context available."];
        }

        const inputText = `${query}\nContext: ${documents.join('\n')}`;
        console.log('Input to Hugging Face API:', inputText); // Log the input

        const response = await axios.post(
            'https://api-inference.huggingface.co/models/google/flan-t5-large', // Use flan-t5 model
            { inputs: inputText },
            {
                headers: {
                    Authorization: `Bearer ${process.env.HUGGINGFACE_API_KEY}`,
                },
            }
        );

        console.log('Hugging Face Response:', response.data); // Log the response
        if (response.data && response.data[0]?.generated_text) {
            return response.data[0].generated_text;
        }

        console.warn('No response generated by Hugging Face API');
        return 'No response generated by AI.';
    } catch (error) {
        console.error('Error generating response from Hugging Face:', error.response?.data || error.message);
        return 'Error generating AI response.';
    }
};

exports.getSimplifiedResponse = async (req, res) => {
    try {
        const { query, videoContext } = req.body;
        const response = await aiService.getResponse(query, videoContext);
        
        if (!response) {
            return res.status(500).json({ message: 'Failed to generate a response from AI.' });
        }

        const savedResponse = await AIAgent.create({ userQuery: query, response, videoContext });
        res.json(savedResponse);
    } catch (error) {
        console.error('Error in getSimplifiedResponse:', error.message);
        res.status(500).json({ message: 'Error processing AI response', error });
    }
};

exports.getResponse = async (query, videoContext) => {
    try {
        // Step 1: Get embeddings for the query
        const embeddings = await this.getEmbeddings(query);

        // Step 2: Retrieve relevant documents based on the context
        let documents = await this.retrieveDocuments(embeddings, videoContext); // Use `let` instead of `const`

        // Step 3: If no documents are found, provide a default context
        if (documents.length === 0) {
            documents = ["RAG stands for Retrieval-Augmented Generation, a model architecture that combines retrieval-based and generative approaches."];
        }

        // Step 4: Generate a response using the retrieved documents
        const response = await this.generateResponse(query, documents);

        return response;
    } catch (error) {
        console.error('Error in getResponse:', error);
        return null;
    }
};